### ISSUE TITLE
Error Fetching Design Tokens

### ISSUE THREAD

**Issue by cwreid** [zeplin/javascript-sdk#1]
When running `zeplinApi.projects.getProjectDesignTokens`, this line:

https://github.com/zeplin/javascript-sdk/blob/5d2bde8d606087903d2fe48b37f97e976b0d3e14/src/models/design-tokens.ts#L43

causes:

```js
error: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at transformJSONToDesignTokens (.../node_modules/@zeplin/sdk/dist/models/design-tokens.js:93:41)
```

Replacing `value.spacings` with `value.spacing` fixes the issue, but not sure if there are other places this change might need to be made.

**Comment by Helehelehele** [comment]
Thanks for reporting this! This should be fixed with the `1.4.2` release.
